### ISSUE TITLE
the addition of overshield has broken all mob health values

### ISSUE THREAD

**Issue by notandvm** [03-JS/Extra-Enchantments-and-Curses#3]
> base 1.20.1 instance
> mods installed are fabric api & eeac
> (screenshots shown use the mod jade for easier viewing of health)

all mobs that have a health value higher than 20 hit-points have been defaulted to 20 (_including boss mobs such as the wither and ender dragon_). if i had to guess this is likely caused by the addition of overshield in 1.6, as this bug isn't present when using version 1.6-b1

(1.6)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/9d028172-0285-4ad1-bc66-ebfb41fffee7)
(1.6-b1)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/0b35ea75-63d6-413d-b6db-b42c2f59e866)

(1.6)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/ba0f562e-cf7d-4c88-a29f-3faae606b25f)
(1.6-b1)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/4da794d6-748b-4729-bf0b-91953e161c88)

(1.6)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/8535e3d9-34b5-4895-8c4a-c7a31f13ed7c)
(1.6-b1)
![image](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/137728158/e1260dc2-1ff3-4a9b-b70f-9332205e366c)

**Comment by 03-JS** [comment]
Overshield is 100% the issue. I have a potential fix in mind but sadly I won't be able to implement it until next wednesday at the very least

**Comment by 03-JS** [comment]
Overshield is 100% the issue. I have a potential fix in mind but I won't be able to test it and implement it until next wendsday at least

**Comment by 03-JS** [comment]
I just managed to fix it. The new version (1.6.1) is available on [modrinth](https://modrinth.com/mod/extra-enchantments-and-curses/versions)
