### ISSUE TITLE
no config option?

### ISSUE THREAD

**Issue by k1r0s** [03-JS/Extra-Enchantments-and-Curses#5]
Hello, I wanted to disable reach enchantment to be only applied to tridents so I can balance that weapon against swords.

thx

**Comment by Zunwolf1896** [comment]
Also looking for a config option, the Swiftness Enchant paired with other mods I have on the server are making things fat to OP and underbalanced, I wanted to locate the config to disabled levels 4-5 but there was no config.

**Comment by 03-JS** [comment]
I'll work on adding a config option in the next update. It'll probably take me a while

**Comment by 03-JS** [comment]
## Some progress on the config screen for Fabric
![2023-11-10_00 58 34](https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/107844615/c690bed1-81aa-429b-8dd1-1d36a3d2da24)

**Comment by 03-JS** [comment]
## Versions [1.8](https://modrinth.com/mod/extra-enchantments-and-curses/version/1.8) and above for Fabric add a config option.

https://github.com/03-JS/Extra-Enchantments-and-Curses/assets/107844615/00d48eec-29a4-467c-8a14-5bed3fc7eeb4

**The Forge version should hopefully be out sometime in the future**
