### ISSUE TITLE
Overshield applying multiple times

### ISSUE THREAD

**Issue by UnlikeAlamo** [03-JS/Extra-Enchantments-and-Curses#7]
When unequipping & re-equipping a piece of armor with overshield, it adds the extra health an additional time. For example: If a chestplate should give me five hearts, when I take it off and put it back on, it will give me 10 hearts. Once more would give me 15 hearts, and this is not reset until I go back to the title screen. 

I understand there is a config file for single player, but I did not see one for my Fabric 1.20.1 server. If you could, please instruct me how to either fix this issue, or disable the enchantment.

**Comment by 03-JS** [comment]
I just tried to recreate the issue but it works fine for me. What version of the mod are you using?

**Comment by UnlikeAlamo** [comment]
I'm using version 1.8.1 with this modpack: https://modrinth.com/modpack/not-a-cult

**Comment by 03-JS** [comment]
Hey, I just tried this modpack and it all worked fine for me. There does seem to be a visual glitch where the extra hearts don't disappear when taking damage after removing the armor, but it's just that, a visual bug. The enchantment never applied more than 5 hearts
