### ISSUE TITLE
Extra enchantment mod and owo-lib crash

### ISSUE THREAD

**Issue by ZerJ704** [03-JS/Extra-Enchantments-and-Curses#8]
I start the game and it crash. I use the extra enchantment mod and owo-lib. Minecraft Fabric 1.20.4

Crash.log: https://gist.github.com/ZerJ704/f9a5dbb0e7a4db88e08e1873cb3d6a01
Latest.log: https://gist.github.com/ZerJ704/a3a1bce998f518e1af1b1f742b078608

**Comment by 03-JS** [comment]
The Fabric version is not available for 1.20.4 yet

**Comment by ZerJ704** [comment]
> The Fabric version is not available for 1.20.4 yet

Yup, my bad. Im not really focus when i read the version. Sorry for this
