### ISSUE TITLE
cant configure mod

### ISSUE THREAD

**Issue by nikolodeon** [03-JS/Extra-Enchantments-and-Curses#9]
I cant seem to configure the mod when using it in forge. There is no config file in the config folder, for Extra enchantments and curses. Also Modmenu is a fabric mod, so i cant configure the mod in game either.

**Comment by 03-JS** [comment]
The Forge version isn't configurable (yet)

**Comment by nikolodeon** [comment]
oh okay that makes more sense then. I'm glad that you write "yet"
